### ISSUE TITLE
TypeError: argument must be an int, or have a fileno() method.

### ISSUE THREAD

**Issue by qwlake** [ppcomp/knu-notice-server#49]
While executing Python multiprocessing(billiard), it comes out this error:
```
celery01       | Exception ignored in: <Finalize object, dead>
celery01       | Traceback (most recent call last):
celery01       |   File "/usr/local/lib/python3.6/multiprocessing/util.py", line 186, in __call__
celery01       |     res = self._callback(*self._args, **self._kwargs)
celery01       |   File "/usr/local/lib/python3.6/site-packages/billiard/managers.py", line 612, in _finalize_manager
celery01       |     process.join(timeout=0.1)
celery01       |   File "/usr/local/lib/python3.6/site-packages/billiard/process.py", line 148, in join
celery01       |     res = self._popen.wait(timeout)
celery01       |   File "/usr/local/lib/python3.6/site-packages/billiard/popen_fork.py", line 54, in wait
celery01       |     if not wait([self.sentinel], timeout):
celery01       |   File "/usr/local/lib/python3.6/site-packages/billiard/connection.py", line 996, in wait
celery01       |     return _poll(object_list, timeout)
celery01       |   File "/usr/local/lib/python3.6/site-packages/billiard/connection.py", line 968, in _poll
celery01       |     pollster.register(fd, select.POLLIN)
celery01       | TypeError: argument must be an int, or have a fileno() method.
```

celery version : 4.4.2
billiard version : 3.6.3.0

I changed celery version 4.4.2 to 5.0.2. So need to monitor weather it sames or not.

**Comment by qwlake** [comment]
Fixed by https://github.com/celery/billiard/issues/270
upgrade to newer version (celery version 4.4.2 -> 5.0.2)
